image: python:3.9-alpine3.18
stages:
  - build
  - test
  - deploy

generate_json:
  stage: build
  script:
    - pip install requests openpyxl==3.0.10
    - ./main.py
  artifacts:
    paths:
      - public/

hsn_sac_tests:
  stage: test
  script:
    - pip install pytest
    - pytest

pages:
  stage: deploy
  script:
    - ls public/
  artifacts:
    paths:
      - public
  only:
    - main
