image: python:alpine
stages:
  - build
  - test
  - deploy

generate_json:
  stage: build
  script:
    - pip install requests openpyxl
    - ./hsn2json.py
    - ./news2json.py
  artifacts:
    paths:
      - json/
      - news/

hsn_sac_tests:
  stage: test
  script:
    - pip install pytest
    - pytest

pages:
  stage: deploy
  script:
    - mkdir tmp
    - mv json tmp/
    - mv news tmp/
    - mv tmp public
  artifacts:
    paths:
      - public
  only:
    - main
